project:
  type: website

website:
  navbar:
    left:
      - href: index.qmd
        text: AEMeR
      - href: https://dnietolugilde.com
        text: Autor
    right:
      - href: index.qmd
        text: "![https://uco.es](img/logo-UCO.jpg){height=1in}"

format:
  html:
    theme: flatly
    css: styles.css
    toc: true
    lang: es
    
execute:
  freeze: auto
