---
title: "Análisis espaciales y multivariantes con R aplicados a estudios de biodiversidad"
subtitle: "Ejercicios de manipulación de datos espaciales"
author: "Diego Nieto Lugilde"
date: 15/10/2024
toc: true
toc-depth: 2
format: 
  html:
    code-fold: true
    code-summary: "Solución (no mirar de primeras)"
editor: visual
---

# Trabajando con datos vectoriales

## Funciones útiles

**`project()`**

Proyecta las coordenadas de los objetos espaciales a un sistema de coordenadas 
diferentes. Para conseguir los códigos EPSG de distintos sistemas de proyeccion
podéis usar la siguiente página: https://epsg.io/

**`[]`**

Los corchetes sirven para extraer elementos de ciertas posiciones en los objetos 
de R. Se pueden usar también con los objetos espaciales

**`==`**

Se usa para realizar comparaciones y generar un vector de valores lógicos que 
indican cuando se cumple una condición de igualdad. 

**`write.`**

## Ejercicios

**1. Cargue los límites administrativos de los departamentos de Argentina en un
objeto llamado "departamentos". Posteriormente, filtre los municipios para retener
sólo los departamentos de la provincia de "Buenos Aires". Finalmente, proyecte 
los datos de estos municipios desde el sistema de coordenadas en longitud-latitud
al sistema UTM21 sur, para lo que podéis usar el código "EPSG:32721". Ahora dibuje 
dos mapas uno con el mapa de la provincia de Buenos Aires en longitud-latitud y
el otro en UTM21s. Por último guarda el objeto vectorial de Buenos Aires con las 
coordenadas en UTM21s como un fichero geopackge nuevo, llamado "BuenosAires.gpkg".**

```{r}
#| warning: false
library(geodata)
departamentos <- gadm("ARG", 2, path = ".")
ba <- departamentos[which(departamentos$NAME_1 == "Buenos Aires")]
ba_utm <- project(ba, "epsg:32721")
par(mfrow = c(1, 2))
plot(ba)
plot(ba_utm)
```
